<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6msxD4P\Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6msxD4P/Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6msxD4P.legacy');

    return;
}

if (!\class_exists(Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\Container6msxD4P\Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer::class, Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer::class, false);
}

return new \Container6msxD4P\Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer([
    'container.build_hash' => '6msxD4P',
    'container.build_id' => 'e302e014',
    'container.build_time' => 1631362228,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6msxD4P');
