<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwAYoSI\Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwAYoSI/Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwAYoSI.legacy');

    return;
}

if (!\class_exists(Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwAYoSI\Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer::class, Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer::class, false);
}

return new \ContainerMwAYoSI\Braunstetter_MenuBundle_Test_app_TestKernelDevDebugContainer([
    'container.build_hash' => 'MwAYoSI',
    'container.build_id' => '91c680e9',
    'container.build_time' => 1630908980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwAYoSI');
