<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'test' => [['name'], ['_controller' => 'Braunstetter\\MenuBundle\\Test\\app\\src\\Controller\\TestController::index'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/test']], [], []],
    'test_one' => [[], ['_controller' => 'Braunstetter\\MenuBundle\\Test\\app\\src\\Controller\\TestController::levelOneRoute'], [], [['text', '/test-one']], [], []],
    'test_two' => [[], ['_controller' => 'Braunstetter\\MenuBundle\\Test\\app\\src\\Controller\\TestController::levelTwoRoute'], [], [['text', '/test-two']], [], []],
    'test_three' => [[], ['_controller' => 'Braunstetter\\MenuBundle\\Test\\app\\src\\Controller\\TestController::levelThreeRoute'], [], [['text', '/test-three']], [], []],
];
