<?php

namespace ContainerNaUkzx3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestEventMenuService extends Braunstetter_MenuBundle_Test_app_src_TestKernelDevDebugContainer
{
    /**
     * Gets the private 'Braunstetter\MenuBundle\Test\app\src\Menu\TestEventMenu' shared service.
     *
     * @return \Braunstetter\MenuBundle\Test\app\src\Menu\TestEventMenu
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contracts/MenuInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Menu.php';
        include_once \dirname(__DIR__, 4).'/tests/app/src/Menu/TestEventMenu.php';

        return $container->privates['Braunstetter\\MenuBundle\\Test\\app\\src\\Menu\\TestEventMenu'] = new \Braunstetter\MenuBundle\Test\app\src\Menu\TestEventMenu(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
